services:
  app:
    build:
      context: .
    container_name: django-app
    ports:
      - "8000:8000"
    entrypoint: sh /tmp/entrypoint.sh
    env_file: ".env"
    networks:
      - default
    volumes:
      - ./app:/app

networks:
  default: